[project]
name = "alignment-methods"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "teepoy", email = "" }
]
requires-python = ">=3.12"
dependencies = [
    "torch>=2.9.1",
]

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
