[project]
name = "data-processing"
version = "0.1.0"
description = "Data processing tools for machine learning projects"
readme = "README.md"
authors = [
    { name = "teepoy", email = "" }
]
requires-python = ">=3.12"
dependencies = [
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "numpy>=1.21.0",
    "pandas>=1.3.0",
    "opencv-python>=4.5.0",
]

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=7.0.0",
]
