# @package _global_
defaults:
  - /base_config
  - _self_

methods:
  kmeans:
    enabled: true
    n_clusters: [2000]
    metric: "cosine"
    random_state: 42
    max_iter: 300
    n_init: 10

  vbgmm:
    enabled: false

  hdbscan:
    enabled: false
