[project]
name = "self-sup-learning"
version = "0.1.0"
description = "Self-supervised learning tools and analysis for machine learning projects"
readme = "README.md"
authors = [
    { name = "teepoy", email = "" }
]
requires-python = ">=3.12"
dependencies = [
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "torchaudio>=2.9.1",
    "numpy>=1.21.0",
    "pandas>=1.3.0",
    "matplotlib>=3.10.7",
    "seaborn>=0.13.2",
    "scikit-learn>=1.7.2",
    "hdbscan>=0.8.40",
    "umap-learn>=0.5.9.post2",
    "transformers>=4.57.3",
    "mmcv==2.1.0",
    "mmengine==0.10.4",
    "mmpretrain==1.2.0",
    "hydra-core>=1.3.2",
]

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=7.0.0",
]
